### ISSUE TITLE
.versatiles created from a GeoJSON isn't being displayed

### ISSUE THREAD

**Issue by kevinvenclovas** [versatiles-org/versatiles-documentation#23]
Hi,

i published the worldmap and a geojson convertet to .versatiles to my google cloud run. Everything is displayed correctly on my server via versatiles frontend.

My map on versatiles frontend 
![image](https://github.com/versatiles-org/versatiles-documentation/assets/7681603/8525f018-8b74-4dff-a77a-5e3aa3a5385a)

My marked location converted from geojson on versatiles frontend 
![image](https://github.com/versatiles-org/versatiles-documentation/assets/7681603/f434d22f-f578-4caa-b574-9f5a424d8efd)

I am currently trying to display my marked location on my map using this code, but I keep receiving a 404 error from each request on my /tiles/testgeo/{z}/{x}/{y} versatiles map.

```
const style = VersaTilesStyle.styles.graybeard({
	  tiles: ['/tiles/osm/{z}/{x}/{y}','/tiles/testgeo/{z}/{x}/{y}'],
	  glyphs: '/assets/fonts/{fontstack}/{range}.pbf',
	  baseUrl: 'https://xxx/',	 
	});

const map = new maplibregl.Map({
	 container: 'map',
	 style : style,		 
    });
````

**How i generated my .versatiles from geojson:**

1. Added on QGIS some areas on a EPSG:3857 Layer.
2. Export Layer as GeoJSON - EPSG:3857
3. Convert the GeoJSON to a .mbtiles: tippecanoe -s EPSG:3857 -o testgeo.mbtiles testgeo.geojson
4. Convert .mbtiles to .versatiles : versatiles convert testgeo.mbtiles testgeo.versatiles

@MichaelKreil can you help me out please?

**Comment by MichaelKreil** [comment]
Ok, I'm still working on the frontend and its documentation. This part is not covered yet, because adding data layers on top of a basemap in MapLibre is a bit tricky. I haven't found a simple solution like a libray, yet. So we will propably have to write our own library at some point, or add features to the style generator.

But now for a solution to your problem:

With `VersaTilesStyle.styles.graybeard({})` you generate a style for rendering the osm data. The parameter `tiles` allows you to set multiple subdomains for the same tile source, but not for different tile sources. So this will not work for adding other data sources, like your "testgeo".

The core of MapLibre is this `style` object (see [spec](https://maplibre.org/maplibre-style-spec/root/)).
It contains an object of data sources (`sources`), and an array of displayed layers (`layers`).
So if you want to put a data visualisation on top of a basemap, you need a style with both data sources in `sources`, and all layers of the basemap and the overlay in `layers`.
The easiest way to do this is to create the basemap style and then "extend" the style by adding the source and layer of the overlay. For example:

```javascript
// style of only the basemap
const style = VersaTilesStyle.styles.graybeard({
   tiles: ['/tiles/osm/{z}/{x}/{y}'],
   glyphs: '/assets/fonts/{fontstack}/{range}.pbf',
   baseUrl: 'https://xxx/',	 
});

// To add testgeo as an overlay, we need to extend the style by:

// ... adding a source for "testgeo" (see: https://maplibre.org/maplibre-style-spec/sources/#vector)
style.sources.testgeo = {
   type: 'vector',
   url: 'https://xxx/tiles/testgeo/tiles.json'
}

// ... and adding a layer for "testgeo" (see: https://maplibre.org/maplibre-style-spec/layers/#circle)
style.layers.push({
	source: 'testgeo', // same name like the key in style.sources,
	source-layer: '...',
	type: 'circle',
	...
})

// create the map
const map = new maplibregl.Map({
   container: 'map',
   style: style,		 
});
```

**Comment by kevinvenclovas** [comment]
Thank you! It's working now with some changes!

Here is my working code:


```
// Create the base map style
const mapstyle = VersaTilesStyle.styles.graybeard({
		tiles: ['/tiles/osm/{z}/{x}/{y}'],
		glyphs: '/assets/fonts/{fontstack}/{range}.pbf',
		baseUrl: 'https://xxx/',	 		
	});

// Create the map
const map = new maplibregl.Map({
		container: 'map',
		style : mapstyle,
    });

// Wait for map style loaded and add the second layer
map.on('style.load', function() {
	
	  map.addSource('testgeo', {
		type: 'vector',
		tiles: ['https://xxx/tiles/testgeo/{z}/{x}/{y}.pbf']	
	  });
	  
	  map.addLayer({
		  'id': 'testgeo-layer',
		  'type': 'fill',
		  'source': 'testgeo-data',
		  'source-layer': 'testgeo', 
		  'paint': {
			'fill-color': 'rgba(255, 0, 0, 0.5)',
			'fill-opacity': 0.5
		  }
		});

	});
```

**Comment by MichaelKreil** [comment]
Looks great.
Adding the source and layer of "testgeo" to the style object might reduce the startup time, since you don't have to wait for the style to load to add the overlay.
